### ISSUE TITLE
Kanboard 1.0.30 - Internal Error: Identifier "config" is not defined.

### ISSUE THREAD

**Issue by crabnky** [Busfreak/kanboard-color_filter#3]
Hi Busfreak,

After upgrade to Kanboard 1.0.30 I ca see the following error:

Internal Error: Identifier "language" is not defined.

Any thoughts?

**Comment by Busfreak** [comment]
Did you try the last version? This works for me.

**Comment by crabnky** [comment]
Yes, I tried.
I made a mistake in the previous post - the error is about config, not language, sorry.
The error is:
Internal Error: Identifier "config" is not defined.

I have the latest version of Kanboard and the latest version of your plugin.

**Comment by Busfreak** [comment]
Sorry, I can't find any error.
I made a fresh installation of KB 1.0.30 and Color_filter 1.2.2. Everything works fine without any change.
Please try the release https://github.com/Busfreak/kanboard-color_filter/releases/download/1.2.2/kanboard-color_filter-1.2.2.zip
With it you can extract directly in the plugins folder without renaming etc.

**Comment by crabnky** [comment]
This is working, thanks! Previously i downloaded version from the github.
Thanks a lot!
